import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster as SonnarToaster } from "@/components/ui/sonner";
import { ThemeProvider } from "./theme/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-indigo-950">
      <body className={`antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <SonnarToaster />
          <TooltipProvider>
            <main className="min-h-screen">{children}</main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
